# Generated by Django 5.2.6 on 2025-09-23 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('categoriaid', models.AutoField(primary_key=True, serialize=False)),
                ('nomecategoria', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'categorias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('cinemaid', models.AutoField(primary_key=True, serialize=False)),
                ('nomecinema', models.CharField(max_length=80)),
                ('emailcinema', models.CharField(blank=True, max_length=254, null=True)),
                ('telefonecinema', models.CharField(blank=True, max_length=20, null=True)),
                ('moradacinema', models.CharField(blank=True, max_length=120, null=True)),
                ('codigopostalcinema', models.CharField(blank=True, max_length=8, null=True)),
                ('localidadecinema', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'cinemas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('clienteid', models.AutoField(primary_key=True, serialize=False)),
                ('nomecliente', models.CharField(blank=True, max_length=80, null=True)),
                ('emailcliente', models.CharField(blank=True, max_length=254, null=True)),
                ('telefonecliente', models.CharField(blank=True, max_length=20, null=True)),
                ('datanascimento', models.DateField(blank=True, null=True)),
                ('moradacliente', models.CharField(blank=True, max_length=120, null=True)),
                ('codigopostalcliente', models.CharField(blank=True, max_length=8, null=True)),
                ('localidadecliente', models.CharField(blank=True, max_length=60, null=True)),
                ('nif', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('produtoid', models.AutoField(primary_key=True, serialize=False)),
                ('nomeproduto', models.CharField(max_length=80)),
                ('precoproduto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.IntegerField()),
                ('ativo', models.BooleanField()),
            ],
            options={
                'db_table': 'produtos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('filmeid', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120)),
                ('datalancamento', models.DateField(blank=True, null=True)),
                ('duracao', models.IntegerField()),
                ('produtora', models.CharField(blank=True, max_length=80, null=True)),
                ('fimexebicao', models.DateField(blank=True, null=True)),
                ('idioma', models.CharField(blank=True, max_length=4, null=True)),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('classificacaoetaria', models.CharField(max_length=6)),
                ('categoriaid', models.ForeignKey(blank=True, db_column='categoriaid', null=True, on_delete=django.db.models.deletion.CASCADE, to='bd2ap1.categorias')),
                ('cinemaid', models.ForeignKey(blank=True, db_column='cinemaid', null=True, on_delete=django.db.models.deletion.CASCADE, to='bd2ap1.cinemas')),
            ],
            options={
                'db_table': 'filmes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('funcionarioid', models.AutoField(primary_key=True, serialize=False)),
                ('nomefuncionario', models.CharField(max_length=80)),
                ('emailfuncionario', models.CharField(blank=True, max_length=254, null=True)),
                ('telefonefuncionario', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(max_length=20)),
                ('admissao', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cinemaid', models.ForeignKey(blank=True, db_column='cinemaid', null=True, on_delete=django.db.models.deletion.CASCADE, to='bd2ap1.cinemas')),
            ],
            options={
                'db_table': 'funcionarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('salaid', models.AutoField(primary_key=True, serialize=False)),
                ('nomesala', models.CharField(blank=True, max_length=80, null=True)),
                ('capacidade', models.IntegerField()),
                ('tiposala', models.CharField(max_length=20)),
                ('cinemaid', models.ForeignKey(blank=True, db_column='cinemaid', null=True, on_delete=django.db.models.deletion.CASCADE, to='bd2ap1.cinemas')),
            ],
            options={
                'db_table': 'salas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('lugarid', models.AutoField(primary_key=True, serialize=False)),
                ('fila', models.CharField(max_length=4)),
                ('numero', models.IntegerField()),
                ('tipolugar', models.CharField(blank=True, max_length=20, null=True)),
                ('estadolugar', models.CharField(blank=True, max_length=20, null=True)),
                ('salaid', models.ForeignKey(blank=True, db_column='salaid', null=True, on_delete=django.db.models.deletion.CASCADE, to='bd2ap1.salas')),
            ],
            options={
                'db_table': 'lugares',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sessoes',
            fields=[
                ('sessaoid', models.AutoField(primary_key=True, serialize=False)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('versao', models.CharField(max_length=8)),
                ('estadosessao', models.CharField(max_length=20)),
                ('precosessao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('filmeid', models.ForeignKey(blank=True, db_column='filmeid', null=True, on_delete=django.db.models.deletion.CASCADE, to='bd2ap1.filmes')),
                ('salaid', models.ForeignKey(blank=True, db_column='salaid', null=True, on_delete=django.db.models.deletion.CASCADE, to='bd2ap1.salas')),
            ],
            options={
                'db_table': 'sessoes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vendalinhas',
            fields=[
                ('vendalinhaid', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('total_linha_field', models.DecimalField(blank=True, db_column='total_linha_', decimal_places=2, max_digits=5, null=True)),
                ('precolinha', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('produtoid', models.ForeignKey(blank=True, db_column='produtoid', null=True, on_delete=django.db.models.deletion.PROTECT, to='bd2ap1.produtos')),
            ],
            options={
                'db_table': 'vendalinhas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bilhetes',
            fields=[
                ('bilheteid', models.AutoField(primary_key=True, serialize=False)),
                ('precobilhete', models.DecimalField(decimal_places=2, max_digits=5)),
                ('emicao', models.DateTimeField()),
                ('lugarid', models.ForeignKey(blank=True, db_column='lugarid', null=True, on_delete=django.db.models.deletion.CASCADE, to='bd2ap1.lugares')),
                ('sessaoid', models.ForeignKey(blank=True, db_column='sessaoid', null=True, on_delete=django.db.models.deletion.CASCADE, to='bd2ap1.sessoes')),
                ('vendalinhaid', models.ForeignKey(blank=True, db_column='vendalinhaid', null=True, on_delete=django.db.models.deletion.CASCADE, to='bd2ap1.vendalinhas')),
            ],
            options={
                'db_table': 'bilhetes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('vendaid', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, null=True)),
                ('estadovenda', models.CharField(blank=True, max_length=20, null=True)),
                ('totalvenda', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('clienteid', models.ForeignKey(blank=True, db_column='clienteid', null=True, on_delete=django.db.models.deletion.CASCADE, to='bd2ap1.clientes')),
                ('funcionarioid', models.ForeignKey(blank=True, db_column='funcionarioid', null=True, on_delete=django.db.models.deletion.CASCADE, to='bd2ap1.funcionarios')),
            ],
            options={
                'db_table': 'vendas',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='vendalinhas',
            name='vendaid',
            field=models.ForeignKey(blank=True, db_column='vendaid', null=True, on_delete=django.db.models.deletion.CASCADE, to='bd2ap1.vendas'),
        ),
    ]
