# Generated by Django 5.2.6 on 2025-09-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bilhetes',
            fields=[
                ('bilheteid', models.AutoField(primary_key=True, serialize=False)),
                ('precobilhete', models.DecimalField(decimal_places=2, max_digits=5)),
                ('emicao', models.DateTimeField()),
            ],
            options={
                'db_table': 'bilhetes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('categoriaid', models.AutoField(primary_key=True, serialize=False)),
                ('nomecategoria', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('cinemaid', models.AutoField(primary_key=True, serialize=False)),
                ('nomecinema', models.CharField(max_length=80)),
                ('emailcinema', models.CharField(blank=True, max_length=254, null=True)),
                ('telefonecinema', models.CharField(blank=True, max_length=20, null=True)),
                ('moradacinema', models.CharField(blank=True, max_length=120, null=True)),
                ('codigopostalcinema', models.CharField(blank=True, max_length=8, null=True)),
                ('localidadecinema', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'cinemas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('clienteid', models.AutoField(primary_key=True, serialize=False)),
                ('nomecliente', models.CharField(blank=True, max_length=80, null=True)),
                ('emailcliente', models.CharField(blank=True, max_length=254, null=True)),
                ('telefonecliente', models.CharField(blank=True, max_length=20, null=True)),
                ('datanascimento', models.DateField(blank=True, null=True)),
                ('moradacliente', models.CharField(blank=True, max_length=120, null=True)),
                ('codigopostalcliente', models.CharField(blank=True, max_length=8, null=True)),
                ('localidadecliente', models.CharField(blank=True, max_length=60, null=True)),
                ('nif', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('filmeid', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120)),
                ('datalancamento', models.DateField(blank=True, null=True)),
                ('duracao', models.IntegerField()),
                ('produtora', models.CharField(blank=True, max_length=80, null=True)),
                ('fimexebicao', models.DateField(blank=True, null=True)),
                ('idioma', models.CharField(blank=True, max_length=4, null=True)),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('classificacaoetaria', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'filmes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('funcionarioid', models.AutoField(primary_key=True, serialize=False)),
                ('nomefuncionario', models.CharField(max_length=80)),
                ('emailfuncionario', models.CharField(blank=True, max_length=254, null=True)),
                ('telefonefuncionario', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(max_length=20)),
                ('admissao', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'funcionarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('lugarid', models.AutoField(primary_key=True, serialize=False)),
                ('fila', models.CharField(max_length=4)),
                ('numero', models.IntegerField()),
                ('tipolugar', models.CharField(blank=True, max_length=20, null=True)),
                ('estadolugar', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'lugares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('produtoid', models.AutoField(primary_key=True, serialize=False)),
                ('nomeproduto', models.CharField(max_length=80)),
                ('precoproduto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.IntegerField()),
                ('ativo', models.BooleanField()),
            ],
            options={
                'db_table': 'produtos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('salaid', models.AutoField(primary_key=True, serialize=False)),
                ('nomesala', models.CharField(blank=True, max_length=80, null=True)),
                ('capacidade', models.IntegerField()),
                ('tiposala', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'salas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessoes',
            fields=[
                ('sessaoid', models.AutoField(primary_key=True, serialize=False)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('versao', models.CharField(max_length=8)),
                ('estadosessao', models.CharField(max_length=20)),
                ('precosessao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'sessoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendalinhas',
            fields=[
                ('vendalinhaid', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('total_linha_field', models.DecimalField(blank=True, db_column='total_linha_', decimal_places=2, max_digits=5, null=True)),
                ('precolinha', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'vendalinhas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('vendaid', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, null=True)),
                ('estadovenda', models.CharField(blank=True, max_length=20, null=True)),
                ('totalvenda', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'vendas',
                'managed': False,
            },
        ),
    ]
