# Generated by Django 5.2.6 on 2026-01-19 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd2ap1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='cartaz_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='cinemaid',
            field=models.ForeignKey(blank=True, db_column='cinemaid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filmes', to='bd2ap1.cinemas'),
        ),
    ]
