# Generated by Django 5.2.8 on 2025-11-23 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd2ap1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendalinhas',
            name='bilheteid',
            field=models.ForeignKey(blank=True, db_column='bilheteid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linhas_venda', to='bd2ap1.bilhetes'),
        ),
    ]
