# Generated by Django 5.2.6 on 2025-09-26 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd2ap1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilhetes',
            name='vendalinhaid',
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='ranking',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Ranking do cinema (0 a 5)', max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='ranking',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Ranking do filme (0 a 5)', max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='ranking',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Ranking do funcionario (0 a 5)', max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
