
# Generated by Django 5.2.6 on 2025-09-27 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd2ap1', '0002_remove_bilhetes_vendalinhaid_alter_cinemas_ranking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendalinhas',
            name='bilheteid',
            field=models.ForeignKey(blank=True, db_column='bilheteid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linhas_venda', to='bd2ap1.bilhetes'),
        ),
    ]
