# Generated by Django 5.2.8 on 2025-11-23 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd2ap1', '0003_alter_vendalinhas_bilheteid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendalinhas',
            name='produtoid',
            field=models.ForeignKey(blank=True, db_column='produtoid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linhas_venda', to='bd2ap1.produtos'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='clienteid',
            field=models.ForeignKey(blank=True, db_column='clienteid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='bd2ap1.clientes'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='funcionarioid',
            field=models.ForeignKey(blank=True, db_column='funcionarioid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='bd2ap1.funcionarios'),
        ),
    ]
