# Generated by Django 5.2.6 on 2025-11-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd2ap1', '0003_vendalinhas_bilheteid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessoes',
            name='fim',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='sessoes',
            name='inicio',
            field=models.TimeField(),
        ),
    ]
