# Generated by Django 5.2.6 on 2026-01-18 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd2ap1', '0001_initial'),
        ('funcionarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funcionario_dados', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='auth_profile', to='bd2ap1.funcionarios', verbose_name='Dados do Funcionário')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_profile', to=settings.AUTH_USER_MODEL, verbose_name='Login do Sistema')),
            ],
            options={
                'verbose_name': 'Perfil de Funcionário',
                'db_table': 'funcionario_profiles',
            },
        ),
    ]
