# Generated by Django 5.2.8 on 2025-11-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd2ap1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
            ],
            options={
                'verbose_name': 'Cinema',
                'verbose_name_plural': 'Cinemas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bd2ap1.cinemas',),
        ),
    ]
