# Generated by Django 5.2.6 on 2025-11-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd2ap1', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bd2ap1.clientes',),
        ),
    ]
