# Generated by Django 5.2.6 on 2026-01-18 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd2ap1', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente_dados', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='auth_profile', to='bd2ap1.clientes', verbose_name='Dados do Cliente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_profile', to=settings.AUTH_USER_MODEL, verbose_name='Login do Sistema')),
            ],
            options={
                'verbose_name': 'Perfil de Cliente',
                'db_table': 'cliente_profiles',
            },
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
